server:
  port : 58888

spring:
  profiles:
    default: standalone
  datasource:
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console:
      '%clr(%d{HH:mm:ss.SSS}){blue} %clr(%-5p) %clr([%8.15t]){cyan} %clr(%-30.30logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'

---

spring:
  config:
    activate:
      on-profile: standalone
  datasource:
    url: jdbc:postgresql://localhost:5439/postgres

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgresdb:5432/postgres
