version: "3"

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"

  postgresdb:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - '5439:5432'

  sender:
    build: sender/.
    ports:
      - 58080:58080
    depends_on:
      - rabbitmq

  listener:
    build: listener/.
    depends_on:
      - rabbitmq
      - postgresdb

  archive:
    build: archive/.
    ports:
      - 58888:58888
    depends_on:
      - postgresdb
