server:
  port : 18080

spring:
  jms:
    pub-sub-domain: true
  profiles:
    default: standalone
  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console:
      '%clr(%d{HH:mm:ss.SSS}){blue} %clr(%-5p) %clr([%8.15t]){cyan} %clr(%-30.30logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'

---

spring:
  config:
    activate:
      on-profile: standalone
  rabbitmq:
    host: localhost

---

spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: rabbitmq
